lint:
  container_configs: false
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - .github/workflows/linting_comment.yml
  files_unchanged: false
  multiqc_config: false
  nextflow_config:
    - config_defaults:
        - params.baktadb
        - params.pfamdb
        - params.macsyfinder_db
  template_strings: false
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: Olga Brovkina
  description: Systems-based bacterial functional modeling pipeline
  force: false
  is_nfcore: true
  name: bacmodel
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
    - gpu
  version: 1.0.0
